### PR TITLE
Split frontend thing-view into view and model to fix memory leak.

### LINKED ISSUE #561: Thing objects leaked in UI
```basic
10 VISIT `/things`
20 CLICK Settings menu item
30 CLICK Things menu item
40 GOTO 20
50 REM some time later...
60 Notice that the server logs are complaining about too many listeners being registered
```

The WebSocket connections will only be closed if you close the tab or browser, not upon garbage collection. This suggests that the Thing objects are never garbage collected, potentially due to the WebSocket's existence.

I think the best way to solve this is to swap to a more explicit Thing lifecycle with attach/detach or view/remove steps.

### LINKED ISSUE #566: Use cached Thing values to speed up Thing details view
All the information should be up to date from the Things list so the Thing view shouldn't need to request everything again

### PR DESCRIPTION
**Pull request by sogaani**
Fixes #561
Fixes #566

### CODE REVIEW

**Comment by sogaani** [comment]
This PR seems to fix https://github.com/mozilla-iot/gateway/issues/566 too.

**Comment by mrstegeman** [comment]
@sogaani Any chance you could rebase this? There has been a ton of churn in this area of the code for the past couple weeks, but it should be back to mostly stable.

**Comment by sogaani** [comment]
@mrstegeman Thank you for ping. I will rebase in this week.

**Comment by sogaani** [comment]
I have finished rebase.

## Performance check.
I recorded memory usage while 60 sec operation among things page, things-detail page and events log page. And I called garbage collection before stop recording.

The Gateway has 9 Things.

### Result
* Master branch
    * Page objects in Heap Memory After recording.
image
    * Heap Memory usage and listeners while recording.
image


* This pull request
    * Page objects in Heap Memory After recording.
image
    * Heap Memory usage and listeners while recording.
image

File: static/js/models/gateway-model.js [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+   *
+   * @param {string} thingId - Id of the thing
+   */
+  removeThing(thingId) {
+    if (!this.thingModels.has(thingId)) {
+      return Promise.reject(`No Thing id:${thingId}`);
+    }
+    return this.addQueue(() => {
+      if (!this.thingModels.has(thingId)) {
+        throw new Error(`Thing id:${thingId} allready removed`);
```
Comment (mrstegeman) [inline static/js/models/gateway-model.js]: s/allready/already/

File: static/js/models/gateway-model.js [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+   * @param {string} thingId - Id of the thing
+   * @param {object} updates - contents of update
+   */
+  updateThing(thingId, updates) {
+    if (!this.thingModels.has(thingId)) {
+      return Promise.reject(`No Thing id:${thingId}`);
+    }
+    return this.addQueue(() => {
+      if (!this.thingModels.has(thingId)) {
+        throw new Error(`Thing id:${thingId} allready removed`);
```
Comment (mrstegeman) [inline static/js/models/gateway-model.js]: s/allready/already/

File: static/js/models/model.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+    if (!this.handlers.has(event)) {
+      return;
+    }
+    const eventHandlers = this.handlers.get(event);
+    for (const handler of eventHandlers.keys()) {
+      try {
+        await handler(state);
+      } catch (e) {
+        console.error(
+          `Error occurs in handler event:${event} state:${state} ${e}`
```
Comment (mrstegeman) [inline static/js/models/model.js]: s/occurs/occurred/

File: static/js/models/thing-model.js [hunk 4]
```diff
@@ -0,0 +1,325 @@
...
+          'Content-Type': 'application/json',
+        },
+      }).then((response) => {
+        if (response.ok) {
+          console.log('Successfully removed Thing.');
+          this.cleanup();
+          resolve();
+        } else {
+          console.error(`Error removing thing ${response.statusText}`);
+          reject();
```
Comment (mrstegeman) [inline static/js/models/thing-model.js]: It would be helpful to pass an error string to `reject()`. Ditto on line 86.

File: static/js/models/thing-model.js [hunk 5]
```diff
@@ -0,0 +1,325 @@
...
+          'Content-Type': 'application/json',
+        },
+        body: JSON.stringify(updates),
+      }).then((response) => {
+        if (response.ok) {
+          console.log('Successfully updated Thing.');
+          resolve();
+        } else {
+          console.error(`Error updating thing ${response.statusText}`);
+          reject();
```
Comment (mrstegeman) [inline static/js/models/thing-model.js]: It would be helpful to pass an error string to `reject()`. Ditto on line 114.

File: static/js/models/thing-model.js [hunk 6]
```diff
@@ -0,0 +1,325 @@
...
+  /**
+   * Set value to the property.
+   *
+   * @param {string} name - name of the property
+   * @param {*} value - value of the property
+   * @return {Promise} which resolves to the property set.
+   */
+  setProperty(name, value) {
+    if (!this.propertyDescriptions.hasOwnProperty(name)) {
+      return Promise.reject();
```
Comment (mrstegeman) [inline static/js/models/thing-model.js]: It would be helpful to pass an error string to `reject()`.

File: static/js/models/thing-model.js [hunk 7]
```diff
@@ -0,0 +1,325 @@
...
+        handler(this.properties);
+        break;
+      default:
+        console.warn(`ThingModel does not support event:${event}`);
+        break;
+    }
+  }
+
+  /**
+   * Set value to the property.
```
Comment (mrstegeman) [inline static/js/models/thing-model.js]: s/to/of/

File: static/js/models/thing-model.js [hunk 8]
```diff
@@ -0,0 +1,325 @@
...
+
+    return fetch(property.href, opts).then((response) => {
+      if (response.status === 200) {
+        return response.json();
+      } else {
+        throw new Error(`Status ${response.status} trying to set ${name}`);
+      }
+    }).then((json) => {
+      this.onPropertyStatus(json);
+    }).catch(function(error) {
```
Comment (mrstegeman) [inline static/js/models/thing-model.js]: nit: Use an arrow function here.

**Comment by sogaani** [comment]
I addressed review other than `an issue when editing a device` and fix conflicts.
I cannot reproduce `an issue when editing a device`...
@mrstegeman do you have reproduce step?

An issue about floorplan fixed on https://github.com/mozilla-iot/gateway/pull/1182, because the issue does not related this pull request.
