### PR TITLE
Fix additional issues with renewal script.

### LINKED ISSUE #1007: My IOT gateway is failing to renew LetsEncrypt cert, with "unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping."
Ever since April 9th[1], it seems my gateway's LetsEncrypt cert renewals have been failing, with error output saying `WARNING:certbot.renewal:Attempting to renew cert from /home/pi/mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping.`  I'm only just noticing this failure this past week, because my last successfully acquired cert has now expired which means I can't access my gateway without SSL-error-page-clickthrough hacks.

Here's a bit more context around that error, from `var/log/letsencrypt.log`, from the first log where this happened:
````2018-04-09 00:00:40,177:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x73bd97d0> and installer None
2018-04-09 00:00:40,181:WARNING:certbot.renewal:Attempting to renew cert from /home/pi/mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping.
2018-04-09 00:00:40,194:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 621, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 399, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 360, in _determine_account
    acc = account_storage.load(config.account)
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 174, in load
    regr = messages.RegistrationResource.json_loads(regr_file.read())
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 180, in json_loads
    return cls.from_json(loads)
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 293, in from_json
    return cls(**cls.fields_from_json(jobj))
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 276, in fields_from_json
    cls._check_required(jobj)
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 271, in _check_required
    ','.join(missing)))
DeserializationError: Deserialization error: The following field are required: new_authzr_uri

2018-04-09 00:00:40,195:DEBUG:certbot.main:Exiting abnormally:
````

[1] (For a large chunk of the time since April 9th, my gateway's LetsEncrypt renewals were actually failing due to a more-proximal issue, #1003, but now that issue's been fixed in trunk and I've hacked around it with local edits, so my gateway is now back to failing renewal due to this issue here.)

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #1007

### CODE REVIEW

File: tools/renew-certificates.sh [hunk 1]
```diff
@@ -10,13 +11,31 @@ for file in $(find "${MOZIOT_HOME}/etc/renewal" -type f -name '*.conf'); do
...
 certbot renew \
     --config-dir "${MOZIOT_HOME}/etc" \
     --logs-dir "${MOZIOT_HOME}/var/log" \
     --work-dir "${MOZIOT_HOME}/var/lib" \
-    --renew-hook "/home/pi/mozilla-iot/gateway/tools/deploy-certificates.sh"
+    --renew-hook "${_dir}/deploy-certificates.sh"
 
-chown -R pi:pi "${MOZIOT_HOME}/etc" "${MOZIOT_HOME}/var"
+# chown the certs as uid/gid 1000, which maps to 'pi' in the Raspberry Pi image,
+# and 'node' in the Docker image.
```
Comment (hobinjk) [inline tools/renew-certificates.sh]: It would be good to make sure that the uid 1000 exists and is pi/node (i.e. be nice to people if this is running on their laptop/generic linux box)

Comment (hobinjk) [reply tools/renew-certificates.sh]: Although the use of MOZIOT_HOME makes it hard to justify adding that logic. I'm okay with or without a check

**Comment by mrstegeman** [comment]
@hobinjk updated.
