### PR TITLE
Stop secondary captive portal after skipping registration.

### LINKED ISSUE #2020: Secondary captive portal stays in effect
On the turris omnia, the secondary captive portal doesn't get shutdown.

I see the following in the log:
```
2019-07-17 00:16:29.063 INFO   : router-setup: stopCaptivePortal
2019-07-17 00:16:37.772 INFO   : router-setup: defineNetwork: ssid: WebThings Gateway
2019-07-17 00:16:38.235 INFO   : router-setup: waitForWifi: connection found
2019-07-17 00:16:38.240 INFO   : router-setup: startSecondaryCaptivePortal: ipaddr: 192.168.2.1
2019-07-17 00:16:38.341 INFO   : Redirecting from 80 to 8080 (for 192.168.2.1)
2019-07-17 00:16:38.523 INFO   : Redirecting from 443 to 4443 (for 192.168.2.1)
2019-07-17 00:16:44.219 INFO   : Stopping Router Setup
2019-07-17 00:16:44.233 INFO   : HTTP server listening on port 8080
2019-07-17 00:16:47.812 INFO   : Loading add-on: thing-url-adapter
2019-07-17 00:16:47.847 INFO   : Loading add-on: zwave-adapter
2019-07-17 00:16:47.922 INFO   : Loading add-on: zigbee-adapter
2019-07-17 00:16:51.517 INFO   : zwave: Opening database: /srv/mozilla-iot-home/config/db.sqlite3
2019-07-17 00:16:51.583 INFO   : zwave: Loading add-on for zwave-adapter from /srv/mozilla-iot-home/addons/zwave-adapter
2019-07-17 00:16:51.667 INFO   : zigbee: Opening database: /srv/mozilla-iot-home/config/db.sqlite3
2019-07-17 00:16:51.683 INFO   : thing-url: Opening database: /srv/mozilla-iot-home/config/db.sqlite3
2019-07-17 00:16:51.746 INFO   : zigbee: Loading add-on for zigbee-adapter from /srv/mozilla-iot-home/addons/zigbee-adapter
2019-07-17 00:16:51.754 INFO   : thing-url: Loading add-on for thing-url-adapter from /srv/mozilla-iot-home/addons/thing-url-adapter
2019-07-17 00:16:52.047 INFO   : zwave: DEBUG config = ''
2019-07-17 00:16:52.073 INFO   : zwave: Closing database
2019-07-17 00:16:52.459 INFO   : thing-url: Starting mDNS discovery
2019-07-17 00:16:52.521 ERROR  : zwave: Failed to load zwave-adapter - Unable to find ZWave adapter
2019-07-17 00:16:52.670 INFO   : zigbee: DEBUG config = ''
2019-07-17 00:16:52.733 INFO   : zigbee: Serial ports that were found:
2019-07-17 00:16:52.771 ERROR  : zigbee: Failed to load zigbee-adapter - No Zigbee dongle found
2019-07-17 00:16:54.365 INFO   : Checking for add-on updates...
2019-07-17 00:16:54.596 INFO   : Finished updating add-ons
2019-07-17 00:29:57.428 INFO   : Tunnel name is set to: Not set.
2019-07-17 00:29:57.429 INFO   : Local mDNS Service Domain Name is: gateway
```
I pressed Skip during the tunnel setup due to #2019 and it went all the way to the Things screen still in the captive portal.
IMG_0435

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #2020

### CODE REVIEW

File: src/controllers/settings_controller.js [hunk 1]
```diff
@@ -135,6 +136,11 @@ SettingsController.post('/subscribe', async (request, response) => {
 SettingsController.post('/skiptunnel', async (request, response) => {
   try {
     await Settings.set('notunnel', true);
+
+    if (Platform.getOS() === 'linux-openwrt') {
+      RouterSetupApp.onSetupComplete();
```
Comment (dhylands) [inline src/controllers/settings_controller.js]: should this go here? or perhaps we should call onSetupComplete at the beginning of startHttpsGateway and startHttpGateway, so that no matter how the gateway gets started we complete setup (if started). The onSetupComplete would just do nothing if setup mode weren't entered.

Comment (mrstegeman) [reply src/controllers/settings_controller.js]: We can't do it inside `startHttpGateway`, because that would kill the secondary captive portal before the user makes it there.
